# Generated by Django 3.1.4 on 2020-12-16 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultship_phone_number', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('defaultship_street_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('defaultship_street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('defaultship_city', models.CharField(blank=True, max_length=40, null=True)),
                ('defaultship_state', models.CharField(blank=True, max_length=80, null=True)),
                ('defaultship_zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
