# Generated by Django 3.1.4 on 2021-01-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201216_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='defaultship_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
