# Generated by Django 3.1.5 on 2021-01-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_userprofile_marketing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='marketing',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
