# Generated by Django 3.1.4 on 2020-12-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_order_credit_card_partial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ship_comp_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
