# Generated by Django 3.1.4 on 2021-01-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-order_date',)},
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
