# Generated by Django 3.1.5 on 2021-04-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20210109_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ca_sales_tax',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
