# Generated by Django 3.1.5 on 2021-10-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_auto_20211024_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productshippingdata',
            options={'ordering': ['product__active', 'product__category__division', 'product__category__name', 'product__product_family__name', 'product__product_size__name'], 'verbose_name_plural': 'Product Shipping Data'},
        ),
    ]
