# Generated by Django 3.1.5 on 2021-10-28 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_auto_20211024_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productshippingdata',
            name='shipper_city',
        ),
        migrations.RemoveField(
            model_name='productshippingdata',
            name='shipper_company_name',
        ),
        migrations.RemoveField(
            model_name='productshippingdata',
            name='shipper_phone_number',
        ),
        migrations.RemoveField(
            model_name='productshippingdata',
            name='shipper_postal_code',
        ),
        migrations.RemoveField(
            model_name='productshippingdata',
            name='shipper_state',
        ),
        migrations.RemoveField(
            model_name='productshippingdata',
            name='shipper_streeline2',
        ),
        migrations.RemoveField(
            model_name='productshippingdata',
            name='shipper_streetline1',
        ),
    ]
