# Generated by Django 3.1.5 on 2021-09-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terms',
            options={'verbose_name_plural': 'Terms'},
        ),
    ]
