# Generated by Django 3.1.5 on 2021-09-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_auto_20210911_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
