# Generated by Django 3.1.5 on 2021-09-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_shipping_subtitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name_plural': 'Shipping'},
        ),
    ]
