# Generated by Django 3.1.4 on 2020-12-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201205_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product_family',
            options={'verbose_name_plural': 'Product_Families'},
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('8oz', '8 oz.'), ('16oz', '16 oz.'), ('18oz', '18 oz.'), ('32oz', '32 oz.'), ('Gallon', 'Gallon')], max_length=254, null=True),
        ),
    ]
