# Generated by Django 3.1.5 on 2021-04-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210331_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('8oz.', '8 oz.'), ('16oz', '16 oz.'), ('18oz', '18 oz.'), ('32oz', '32 oz.'), ('Gallon', 'Gallon'), ('.9diameter', '.9 in. diameter'), ('2.6x12', '2.6 in. x 12 in.'), ('3.375x3.375', '3.375 in. x 3.375 in.'), ('3x4', '3 in. x 4 in.'), ('4inLength-custom avail', '4 in. length - custom available'), ('4x3.625', '4 in. x 3.625 in.'), ('4x6', '4 in. x 6 in.'), ('4x9', '4 in. x 9 in.'), ('4x18', '4 in. x 18 in.'), ('6x9', '6 in. x 9 in.'), ('7x10', '7 in. x 10 in.'), ('7x17', '7 in. x 17 in.'), ('9x12', '9 in. x 12 in.'), ('9.125x2.1875x4.875', '9.125 in. x 2.1875 in. x 4.875 in.'), ('11x17', '11 in. x 17 in.'), ('12x18', '12 in. x 18 in.'), ('12.125x16.875', '12.125 in. x 16.875 in.'), ('12x18', '12 in. x 18 in.'), ('48x12x5', '48 in. x 12 in. x 5 in.'), ('48x16x5', '48 in. x 16 in. x 5 in.')], max_length=254, null=True),
        ),
    ]
