# Generated by Django 3.1.5 on 2021-07-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210703_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__division', 'category__name']},
        ),
    ]
