# Generated by Django 3.1.5 on 2021-07-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210704_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__division', 'category__name', 'product_family__name', 'size']},
        ),
    ]
