# Generated by Django 3.1.5 on 2021-09-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210911_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category__division', 'category__name', 'product_family__name', 'product_size']},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['name'], 'verbose_name_plural': 'ProductSizes'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
