# Generated by Django 3.1.5 on 2021-10-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210911_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['name'], 'verbose_name_plural': 'Product Sizes'},
        ),
    ]
